CartPole-v1:
  normalize: True
  n_envs: 8
  n_timesteps: !!float 1e5
  policy: 'MlpLstmPolicy'
  n_steps: 32
  batch_size: 256
  gae_lambda: 0.348
  gamma: 1.253
  n_epochs: 20
  ent_coef: 0.52
  vf_coef: 0.515
  learning_rate: lin_0.009
  clip_range: lin_0.922
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"



BipedalWalker-v3:
  normalize: true
  n_envs: 32
  n_timesteps: !!float 5e6
  policy: 'MlpLstmPolicy'
  n_steps: 256
  batch_size: 256
  gae_lambda: 0.95
  gamma: 0.999
  n_epochs: 10
  ent_coef: 0.0
  learning_rate: !!float 3e-4
  clip_range: 0.18
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"

