Acrobot-v1:
  normalize: true
  n_envs: 16
  n_timesteps: !!float 1e6
  policy: 'MlpLstmPolicy'
  n_steps: 256
  n_epochs: 4
  gae_lambda: 0.674
  gamma: 1.115
  learning_rate: 0.005
  clip_range: 0.853
  ent_coef: 0.222
  vf_coef: 0.739


LunarLander-v2: &lunar-defaults
  normalize: True
  n_envs: 32
  n_timesteps: !!float 5e6
  policy: 'MlpLstmPolicy'
  n_steps: 512
  batch_size: 128
  gae_lambda: 0.833
  gamma: 0.708
  learning_rate: 0.819
  clip_range: 0.938
  n_epochs: 4
  ent_coef: 0.953
  vf_coef: 0.827
  policy_kwargs: "dict(
                    ortho_init=False,
                    activation_fn=nn.ReLU,
                    lstm_hidden_size=64,
                    enable_critic_lstm=True,
                    net_arch=dict(pi=[64], vf=[64])
                  )"